# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ishank Gulati
tagline:             'BTech student at Malaviya National Institute of Technology'
description:         'Learn Improvise Innovate Repeat'
url:                 http://ishankgulati.github.io
giturl:				 http://ishankgulati.github.io
baseurl:             http://ishankgulati.github.io/
paginate:            5
paginate_path:       "blog/page:num"
rss:                 atom.xml

# About/contact
author:
  name:             Ishank Gulati
  github:           IshankGulati
  email:            gulati.ishank@gmail.com
  linkedin:         ishankgulati
  gravatar_md5:     01f7b07a31316e30cdfe827e2fc68e7c

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/IshankGulati/ishankgulati.github.io